name: Lock Issue and Assign Labels

on:
  issues:
    types: labeled

permissions:
  issues: write
  
jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/label-actions@v3
        with:
          process-only: issues
          config-path: .github/config/issue-lock-unlock.yml
          github-token: ${{ secrets.GITHUB_TOKEN }}
